# GitHub Pages config
title: "Στοιχεία Γραμμικής Άλγεβρας και Στοιχεία Διαφορικού και Ολοκληρωτικού Λογισμού"
description: "Ψηφιακό συνοδευτικό υλικό: διαδραστικά κουίζ, δραστηριότητες CAS και animations"
url: "https://nikmatz.github.io"
baseurl: "/ELADIC_GR"
theme: null
plugins: []
